#!/bin/bash

REPOHOME=/global/cscratch1/sd/alsina/alpha-beta-gamma/code
STARS=/global/cscratch1/sd/seccolf/y3a1-v29
OUT=/global/cscratch1/sd/alsina/alpha-beta-gamma/out

# source /global/common/software/des/zuntz/setup
source /global/common/software/des/zuntz/setup-nompi

cd $REPOHOME
python reserved_stars_corr.py --piff_cat=$STARS --exps_file=ally3.grizY --outpath=$OUT --bands=riz

